const $=id=>document.getElementById(id);
async function api(url, options={}){const res=await fetch(url,{credentials:'same-origin',...options});let data=null;try{data=await res.json()}catch(e){}if(!res.ok)throw new Error((data&&data.error)||('HTTP '+res.status));return data}
function setStatus(id,msg,ok=false){const el=$(id);el.textContent=msg||'';el.className='status '+(ok?'ok':msg?'error':'')}
function bind(id,event,handler){const el=$(id);if(el)el.addEventListener(event,handler);return el}
async function checkSession(){try{await api('/api/admin/session');showAdmin()}catch(e){showLogin()}}
function showLogin(){$('loginCard').hidden=false;$('adminMain').hidden=true;$('logoutBtn').hidden=true}
function showAdmin(){$('loginCard').hidden=true;$('adminMain').hidden=false;$('logoutBtn').hidden=false;loadAll();startUsageTimer()}
async function loadAll(){await Promise.allSettled([loadUsage(),loadFeedback(),loadStatus(),loadBackups(),loadSiteNotice()])}
async function loadUsage(){const data=await api('/api/admin/usage');$('usageActive').textContent=data.activeUsers||0;$('usageTotal').textContent=data.totalUses||0}
function startUsageTimer(){if(window.__usageTimer)return;window.__usageTimer=setInterval(()=>{if(!$('adminMain').hidden)loadUsage().catch(()=>{})},15000)}
async function loadFeedback(){const data=await api('/api/admin/feedback?limit=80');$('feedbackTotal').textContent=data.total+' 条';$('feedbackMetric').textContent=data.total||0;$('feedbackRows').innerHTML=data.items.map(item=>'<tr><td>'+esc(item.created_at)+'</td><td>'+esc(item.employeeId)+'</td><td><pre>'+esc(item.suggestion)+'</pre></td><td>'+esc(item.ip||'')+'</td></tr>').join('')||'<tr><td colspan="4" class="muted">暂无反馈</td></tr>'}
async function loadStatus(){const data=await api('/api/admin/database/status');const products=data.meta&&data.meta.product_count;const params=data.meta&&data.meta.parameter_count;$('databaseMetric').textContent=(products||0)+' / '+(params||0);$('databaseMetricSub').textContent='产品 / 参数';$('dbStatus').textContent='产品 '+(products||'-')+'，参数 '+(params||'-')+'，更新时间 '+(data.meta&&data.meta.built_at||'-')}
async function loadBackups(){const data=await api('/api/admin/upgrade/backups');$('dbBackups').innerHTML=(data.databaseBackups||[]).map(b=>`<button class="btn secondary" onclick="rollbackDatabase('${escAttr(b.name)}')">${esc(b.name)}</button>`).join('')||'<div class="muted">暂无数据库备份</div>';$('codeBackups').innerHTML=(data.codeBackups||[]).map(b=>`<button class="btn secondary" onclick="rollbackCode('${escAttr(b.name)}')">${esc(b.name)} · ${formatSize(b.size)} · 回滚并重启</button>`).join('')||'<div class="muted">暂无代码备份</div>';$('applyUpgradeBtn').disabled=!(data.pending&&data.pending.canApply);$('lastUpgradeStatus').innerHTML=renderLastUpgrade(data.lastUpgrade);if(data.pending&&data.pending.report){$('upgradeReport').innerHTML=renderUpgradeReport(data.pending.report)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function escAttr(v){return esc(v).replace(/\\/g,'\\\\').replace(/'/g,'&#39;')}
function formatSize(size){const n=Number(size)||0;if(n>1024*1024)return(n/1024/1024).toFixed(1)+' MB';if(n>1024)return(n/1024).toFixed(1)+' KB';return n+' B'}
function renderUpgradeReport(report){if(!report)return'';const errors=(report.errors||[]).map(x=>'<li>'+esc(x)+'</li>').join('');const warnings=(report.warnings||[]).map(x=>'<li>'+esc(x)+'</li>').join('');return '<div><b>'+(report.canApply?'预检通过':'预检未通过')+'</b> · 文件 '+esc(report.fileCount||0)+' · 目录 '+esc((report.directories||[]).join(', ')||'-')+'</div>'+(errors?'<ul>'+errors+'</ul>':'')+(warnings?'<ul>'+warnings+'</ul>':'')}
function renderHealth(checks){return (checks||[]).map(c=>esc(c.path)+': '+esc(c.status)+' '+(c.ok?'OK':'FAIL')).join('；')}
function renderLastUpgrade(log){if(!log)return'<span class="muted">暂无升级记录</span>';return '<b>'+esc(log.status||'-')+'</b> · '+esc(log.updatedAt||'-')+(log.backup?' · 备份 '+esc(log.backup):'')+(log.healthChecks?' · '+renderHealth(log.healthChecks):'')}
function getNoticePayload(){return{enabled:$('noticeEnabled').checked,title:$('noticeTitle').value.trim().slice(0,40),message:$('noticeMessage').value.trim().slice(0,300)}}
function fillSiteNotice(data){$('noticeEnabled').checked=!!(data&&data.enabled);$('noticeTitle').value=(data&&data.title)||'';$('noticeMessage').value=(data&&data.message)||'';renderNoticePreview(false)}
async function loadSiteNotice(){const data=await api('/api/admin/site-notice');fillSiteNotice(data)}
function renderNoticePreview(showEmpty=true){const data=getNoticePayload();const box=$('noticePreview');const visible=!!(data.message||showEmpty);box.hidden=!visible;if(!visible)return;box.innerHTML='<strong>'+esc(data.title||'通知')+'</strong>'+(data.message?esc(data.message):'<span class="muted">通知内容为空，前台不会显示。</span>')}
async function saveSiteNotice(){try{const payload=getNoticePayload();const data=await api('/api/admin/site-notice',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});fillSiteNotice(data.notice);setStatus('noticeStatus','通知已保存'+(data.notice.enabled?'，前台将显示。':'，前台不会显示。'),true)}catch(e){setStatus('noticeStatus',e.message)}}
bind('loginBtn','click',async()=>{try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});showAdmin()}catch(e){setStatus('loginStatus',e.message)}});
bind('logoutBtn','click',async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});showLogin()});
bind('refreshFeedbackBtn','click',loadFeedback);bind('refreshStatusBtn','click',loadStatus);bind('reloadBtn','click',()=>location.reload());
bind('previewNoticeBtn','click',()=>renderNoticePreview(true));bind('saveNoticeBtn','click',saveSiteNotice);
bind('uploadDbBtn','click',async()=>{const file=$('dbFile').files[0];if(!file)return setStatus('dbStatus','请选择数据库文件');const fd=new FormData();fd.append('database',file);try{const data=await api('/api/admin/database/upload',{method:'POST',body:fd});setStatus('dbStatus','已应用：产品 '+data.meta.product_count+'，参数 '+data.meta.parameter_count,true);loadBackups()}catch(e){setStatus('dbStatus',e.message)}});
bind('uploadZipBtn','click',async()=>{const file=$('zipFile').files[0];if(!file)return setStatus('upgradeStatus','请选择 ZIP 文件');const fd=new FormData();fd.append('package',file);try{const data=await api('/api/admin/upgrade/upload',{method:'POST',body:fd});$('upgradeReport').innerHTML=renderUpgradeReport(data.report);$('applyUpgradeBtn').disabled=!data.canApply;setStatus('upgradeStatus',data.canApply?'预检通过，可以执行影子验证。':'预检未通过，正式服务未受影响。',data.canApply);loadBackups()}catch(e){$('applyUpgradeBtn').disabled=true;setStatus('upgradeStatus',e.message)}});
function restartHint(data,doneText){return data.restartScheduled ? doneText+'，服务即将重启。' : doneText+'。当前未检测到守护模式或 PM2。'}
bind('applyUpgradeBtn','click',async()=>{if(!confirm('确认执行影子验证并应用？只有影子服务健康检查通过后才会切换正式代码。'))return;try{const data=await api('/api/admin/upgrade/apply',{method:'POST'});setStatus('upgradeStatus',restartHint(data,'已通过影子验证并应用')+' 备份：'+data.backup+'；健康检查：'+renderHealth(data.healthChecks),true);$('applyUpgradeBtn').disabled=true;loadBackups()}catch(e){setStatus('upgradeStatus',e.message)}});
bind('restartBtn','click',async()=>{if(!confirm('确认重启服务？仅守护模式或 PM2 启动时可自动拉起。'))return;try{const data=await api('/api/admin/system/restart',{method:'POST'});setStatus('systemStatus',restartHint(data,'已提交重启'),true)}catch(e){setStatus('systemStatus',e.message)}});
async function rollbackCode(name){if(!confirm('确认影子验证并回滚代码？验证通过后会自动重启。'))return;try{const data=await api('/api/admin/upgrade/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:name})});setStatus('upgradeStatus',restartHint(data,'已通过影子验证并回滚')+' 回滚目标：'+data.backup+'；当前备份：'+data.currentBackup,true);loadBackups()}catch(e){setStatus('upgradeStatus',e.message)}}
async function rollbackDatabase(name){if(!confirm('确认恢复数据库备份？'))return;try{const data=await api('/api/admin/database/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:name})});setStatus('dbStatus','已恢复：'+data.backup,true);loadStatus()}catch(e){setStatus('dbStatus',e.message)}}
checkSession();
