const $=id=>document.getElementById(id);
async function api(url, options={}){const res=await fetch(url,{credentials:'same-origin',...options});let data=null;try{data=await res.json()}catch(e){}if(!res.ok)throw new Error((data&&data.error)||('HTTP '+res.status));return data}
function setStatus(id,msg,ok=false){const el=$(id);el.textContent=msg||'';el.className='status '+(ok?'ok':msg?'error':'')}
function bind(id,event,handler){const el=$(id);if(el)el.addEventListener(event,handler);return el}
async function checkSession(){try{await api('/api/admin/session');showAdmin()}catch(e){showLogin()}}
function showLogin(){$('loginCard').hidden=false;$('adminMain').hidden=true;$('logoutBtn').hidden=true}
function showAdmin(){$('loginCard').hidden=true;$('adminMain').hidden=false;$('logoutBtn').hidden=false;loadAll();startUsageTimer()}
async function loadAll(){await Promise.allSettled([loadUsage(),loadAnalytics(),loadFeedback(),loadStatus(),loadBackups(),loadSiteNotice(),loadAppSettings(),loadTransferFiles()])}
async function loadUsage(){const data=await api('/api/admin/usage');$('usageActive').textContent=data.activeUsers||0;$('usageTotal').textContent=data.totalUses||0}
function startUsageTimer(){if(window.__usageTimer)return;window.__usageTimer=setInterval(()=>{if(!$('adminMain').hidden){loadUsage().catch(()=>{});loadAnalytics().catch(()=>{})}},15000)}
async function loadFeedback(){const data=await api('/api/admin/feedback?limit=80');$('feedbackTotal').textContent=data.total+' 条';$('feedbackMetric').textContent=data.total||0;$('feedbackRows').innerHTML=data.items.map(item=>`<tr><td><input class="feedback-check" type="checkbox" title="标记" ${item.handled?'checked':''} onchange="toggleFeedbackHandled(this,'${escAttr(item.id)}')"></td><td>${formatTime(item.created_at)}</td><td>${esc(item.employeeId)}</td><td><pre>${esc(item.suggestion)}</pre></td><td>${esc(item.ip||'')}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">暂无反馈</td></tr>'}
async function loadStatus(){const data=await api('/api/admin/database/status');const products=data.meta&&data.meta.product_count;const params=data.meta&&data.meta.parameter_count;$('databaseMetric').textContent=(products||0)+' / '+(params||0);$('databaseMetricSub').textContent='产品 / 参数';$('dbStatus').textContent='产品 '+(products||'-')+'，参数 '+(params||'-')+'，更新时间 '+(data.meta&&data.meta.built_at||'-')}
async function loadBackups(){const data=await api('/api/admin/upgrade/backups');$('dbBackups').innerHTML=(data.databaseBackups||[]).map(b=>`<button class="btn secondary" onclick="rollbackDatabase('${escAttr(b.name)}')">${esc(b.name)}</button>`).join('')||'<div class="muted">暂无数据库备份</div>';$('codeBackups').innerHTML=(data.codeBackups||[]).map(b=>`<button class="btn secondary" onclick="rollbackCode('${escAttr(b.name)}')">${esc(b.name)} · ${formatSize(b.size)} · 回滚并重启</button>`).join('')||'<div class="muted">暂无代码备份</div>';$('applyUpgradeBtn').disabled=!(data.pending&&data.pending.canApply);$('lastUpgradeStatus').innerHTML=renderLastUpgrade(data.lastUpgrade);if(data.pending&&data.pending.report){$('upgradeReport').innerHTML=renderUpgradeReport(data.pending.report)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function escAttr(v){return esc(v).replace(/\\/g,'\\\\').replace(/'/g,'&#39;')}
function formatSize(size){const n=Number(size)||0;if(n>1024*1024)return(n/1024/1024).toFixed(1)+' MB';if(n>1024)return(n/1024).toFixed(1)+' KB';return n+' B'}
function formatNumber(value){return String(Math.max(0,Number(value)||0))}
function formatPercent(value){return ((Number(value)||0)*100).toFixed(1).replace(/\.0$/,'')+'%'}
function formatDuration(ms){const n=Math.max(0,Number(ms)||0);if(!n)return'-';if(n>=60000)return(n/60000).toFixed(1).replace(/\.0$/,'')+' 分钟';return Math.round(n/1000)+' 秒'}
function formatTime(value){if(!value)return'-';const date=new Date(value);if(Number.isNaN(date.getTime()))return esc(value);return date.toLocaleString('zh-CN',{hour12:false})}
function formatVisitorId(value){const text=String(value||'').trim();if(!text)return'-';return text.length>18?text.slice(0,10)+'...'+text.slice(-6):text}
function metricItem(label,value){return'<div class="analytics-item"><b>'+esc(value)+'</b><span>'+esc(label)+'</span></div>'}
function todayInputValue(){const now=new Date();const local=new Date(now.getTime()-now.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function ensureAnalyticsDateInputs(){const start=$('analyticsStartDate');const end=$('analyticsEndDate');if(!start||!end)return;const today=todayInputValue();if(!start.value)start.value=today;if(!end.value)end.value=today}
function getAnalyticsRangeQuery(){ensureAnalyticsDateInputs();const start=$('analyticsStartDate')&&$('analyticsStartDate').value;const end=$('analyticsEndDate')&&$('analyticsEndDate').value;const params=new URLSearchParams();if(start)params.set('start',start);if(end)params.set('end',end);return params.toString()}
async function loadAnalytics(){ensureAnalyticsDateInputs();const query=getAnalyticsRangeQuery();const data=await api('/api/admin/analytics'+(query?'?'+query:''));const rangeTotals=data.rangeTotals||data.today||{};const totals=data.totals||{};const range=data.range||{};const totalGenerate=Number(rangeTotals.generateTotal)||0;const successRate=totalGenerate?(Number(rangeTotals.generateSuccess)||0)/totalGenerate:0;const avgMs=Number(rangeTotals.generateSuccess)?(Number(rangeTotals.generateSuccessDurationMs)||0)/(Number(rangeTotals.generateSuccess)||1):0;$('analyticsRangeText').textContent='当前范围：'+(range.label||'今日');$('todayVisitUsers').textContent=formatNumber(rangeTotals.visitUserCount);$('todayVisits').textContent=formatNumber(rangeTotals.visitSessions);$('todayGenerates').textContent=formatNumber(rangeTotals.generateTotal);$('totalGenerates').textContent=formatNumber(totals.generateTotal);$('generateSuccessRate').textContent=formatPercent(successRate);$('avgGenerateDuration').textContent=formatDuration(avgMs);$('aiAnalyticsGrid').innerHTML=[metricItem('范围生成成功',formatNumber(rangeTotals.generateSuccess)),metricItem('范围生成失败',formatNumber(rangeTotals.generateFailure)),metricItem('AI 改写成功',formatNumber(rangeTotals.rewriteSuccess)),metricItem('AI 改写失败',formatNumber(rangeTotals.rewriteFailure)),metricItem('格式整理成功',formatNumber(rangeTotals.formatSuccess)),metricItem('格式整理失败',formatNumber(rangeTotals.formatFailure)),metricItem('AI 任务失败总数',formatNumber(rangeTotals.failureTotal)),metricItem('历史生成总数',formatNumber(totals.generateTotal))].join('');$('visitorRows').innerHTML=(data.sources||[]).map(item=>'<tr><td title="'+escAttr(item.visitorId||'')+'">'+esc(formatVisitorId(item.visitorId))+'</td><td>'+(item.rangeVisited?'是':'否')+'</td><td>'+formatNumber(item.generateTotal)+'</td><td>'+formatNumber(item.generateSuccess)+'</td><td>'+formatNumber(item.generateFailure)+'</td><td>'+formatPercent(item.generateSuccessRate)+'</td><td>'+formatNumber(item.rewriteSuccess)+'</td><td>'+formatNumber(item.formatSuccess)+'</td><td>'+formatTime(item.lastSeenAt)+'</td></tr>').join('')||'<tr><td colspan="9" class="muted">暂无访问端数据</td></tr>';$('failureRows').innerHTML=(data.failures||[]).map(item=>'<tr><td>'+esc(item.code||'-')+'</td><td><b>'+esc(item.label||'-')+'</b><small>'+esc(item.reason||'')+'</small></td><td>'+esc(item.suggestion||'-')+'</td><td>'+formatNumber(item.count)+'</td><td>'+formatTime(item.lastSeenAt)+'</td></tr>').join('')||'<tr><td colspan="5" class="muted">暂无失败记录</td></tr>'}
function renderUpgradeReport(report){if(!report)return'';const errors=(report.errors||[]).map(x=>'<li>'+esc(x)+'</li>').join('');const warnings=(report.warnings||[]).map(x=>'<li>'+esc(x)+'</li>').join('');return '<div><b>'+(report.canApply?'预检通过':'预检未通过')+'</b> · 文件 '+esc(report.fileCount||0)+' · 目录 '+esc((report.directories||[]).join(', ')||'-')+'</div>'+(errors?'<ul>'+errors+'</ul>':'')+(warnings?'<ul>'+warnings+'</ul>':'')}
function renderHealth(checks){return (checks||[]).map(c=>esc(c.path)+': '+esc(c.status)+' '+(c.ok?'OK':'FAIL')).join('；')}
function renderLastUpgrade(log){if(!log)return'<span class="muted">暂无升级记录</span>';return '<b>'+esc(log.status||'-')+'</b> · '+esc(log.updatedAt||'-')+(log.backup?' · 备份 '+esc(log.backup):'')+(log.healthChecks?' · '+renderHealth(log.healthChecks):'')}
function getNoticePayload(){return{enabled:$('noticeEnabled').checked,title:$('noticeTitle').value.trim().slice(0,40),message:$('noticeMessage').value.trim().slice(0,300)}}
function fillSiteNotice(data){$('noticeEnabled').checked=!!(data&&data.enabled);$('noticeTitle').value=(data&&data.title)||'';$('noticeMessage').value=(data&&data.message)||'';renderNoticePreview(false)}
async function loadSiteNotice(){const data=await api('/api/admin/site-notice');fillSiteNotice(data)}
function renderNoticePreview(showEmpty=true){const data=getNoticePayload();const box=$('noticePreview');const visible=!!(data.message||showEmpty);box.hidden=!visible;if(!visible)return;box.innerHTML='<strong>'+esc(data.title||'通知')+'</strong>'+(data.message?esc(data.message):'<span class="muted">通知内容为空，前台不会显示。</span>')}
async function saveSiteNotice(){try{const payload=getNoticePayload();const data=await api('/api/admin/site-notice',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});fillSiteNotice(data.notice);setStatus('noticeStatus','通知已保存'+(data.notice.enabled?'，前台将显示。':'，前台不会显示。'),true)}catch(e){setStatus('noticeStatus',e.message)}}
function fillAppSettings(data){$('mobileEnabled').checked=!!(data&&data.mobileEnabled)}
async function loadAppSettings(){const data=await api('/api/admin/app-settings');fillAppSettings(data);setStatus('appSettingsStatus',data.mobileEnabled?'手机端界面已启用':'手机端界面已关闭',true)}
async function saveAppSettings(){try{const payload={mobileEnabled:$('mobileEnabled').checked};const data=await api('/api/admin/app-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});fillAppSettings(data.settings);setStatus('appSettingsStatus',data.settings.mobileEnabled?'已启用手机端界面':'已关闭手机端界面，手机访问将提示在电脑工作台操作',true)}catch(e){setStatus('appSettingsStatus',e.message)}}
async function loadTransferFiles(){const box=$('transferFiles');if(!box)return;try{const data=await api('/api/admin/file-channel/list?limit=30');box.innerHTML=(data.files||[]).map(file=>`<div class="file-item"><div><b>${esc(file.originalName||file.name)}</b><span>${esc(file.uploadedAt||'-')} · ${formatSize(file.size)} · ${esc(file.path||'')}</span></div><a class="btn secondary" href="/api/admin/file-channel/download?name=${encodeURIComponent(file.name)}" target="_blank" rel="noopener">下载</a></div>`).join('')||'<div class="muted">暂无传输文件</div>'}catch(e){box.innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
async function uploadTransferFile(){const file=$('transferFile').files[0];if(!file)return setStatus('transferStatus','请选择要传给服务器的文件');const fd=new FormData();fd.append('transfer',file);try{const data=await api('/api/admin/file-channel/upload',{method:'POST',body:fd});setStatus('transferStatus','已上传：'+data.file.originalName+' → '+data.file.path,true);$('transferFile').value='';loadTransferFiles()}catch(e){setStatus('transferStatus',e.message)}}
async function toggleFeedbackHandled(input,id){const checked=!!(input&&input.checked);if(input)input.disabled=true;try{await api('/api/admin/feedback/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,handled:checked})})}catch(e){if(input)input.checked=!checked;alert(e.message||'反馈状态保存失败')}finally{if(input)input.disabled=false}}
bind('loginBtn','click',async()=>{try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});showAdmin()}catch(e){setStatus('loginStatus',e.message)}});
bind('logoutBtn','click',async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});showLogin()});
bind('refreshFeedbackBtn','click',loadFeedback);bind('refreshStatusBtn','click',loadStatus);bind('reloadBtn','click',()=>location.reload());
bind('applyAnalyticsRangeBtn','click',loadAnalytics);bind('todayAnalyticsRangeBtn','click',()=>{const today=todayInputValue();$('analyticsStartDate').value=today;$('analyticsEndDate').value=today;loadAnalytics()});
bind('previewNoticeBtn','click',()=>renderNoticePreview(true));bind('saveNoticeBtn','click',saveSiteNotice);
bind('saveAppSettingsBtn','click',saveAppSettings);
bind('uploadTransferBtn','click',uploadTransferFile);bind('refreshTransferBtn','click',loadTransferFiles);
bind('uploadDbBtn','click',async()=>{const file=$('dbFile').files[0];if(!file)return setStatus('dbStatus','请选择数据库文件');const fd=new FormData();fd.append('database',file);try{const data=await api('/api/admin/database/upload',{method:'POST',body:fd});setStatus('dbStatus','已应用：产品 '+data.meta.product_count+'，参数 '+data.meta.parameter_count,true);loadBackups()}catch(e){setStatus('dbStatus',e.message)}});
bind('uploadZipBtn','click',async()=>{const file=$('zipFile').files[0];if(!file)return setStatus('upgradeStatus','请选择 ZIP 文件');const fd=new FormData();fd.append('package',file);try{const data=await api('/api/admin/upgrade/upload',{method:'POST',body:fd});$('upgradeReport').innerHTML=renderUpgradeReport(data.report);$('applyUpgradeBtn').disabled=!data.canApply;setStatus('upgradeStatus',data.canApply?'预检通过，可以执行影子验证。':'预检未通过，正式服务未受影响。',data.canApply);loadBackups()}catch(e){$('applyUpgradeBtn').disabled=true;setStatus('upgradeStatus',e.message)}});
function restartHint(data,doneText){return data.restartScheduled ? doneText+'，服务即将重启。' : doneText+'。当前未检测到守护模式或 PM2。'}
bind('applyUpgradeBtn','click',async()=>{if(!confirm('确认执行影子验证并应用？只有影子服务健康检查通过后才会切换正式代码。'))return;try{const data=await api('/api/admin/upgrade/apply',{method:'POST'});setStatus('upgradeStatus',restartHint(data,'已通过影子验证并应用')+' 备份：'+data.backup+'；健康检查：'+renderHealth(data.healthChecks),true);$('applyUpgradeBtn').disabled=true;loadBackups()}catch(e){setStatus('upgradeStatus',e.message)}});
bind('restartBtn','click',async()=>{if(!confirm('确认重启服务？仅守护模式或 PM2 启动时可自动拉起。'))return;try{const data=await api('/api/admin/system/restart',{method:'POST'});setStatus('systemStatus',restartHint(data,'已提交重启'),true)}catch(e){setStatus('systemStatus',e.message)}});
async function rollbackCode(name){if(!confirm('确认影子验证并回滚代码？验证通过后会自动重启。'))return;try{const data=await api('/api/admin/upgrade/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:name})});setStatus('upgradeStatus',restartHint(data,'已通过影子验证并回滚')+' 回滚目标：'+data.backup+'；当前备份：'+data.currentBackup,true);loadBackups()}catch(e){setStatus('upgradeStatus',e.message)}}
async function rollbackDatabase(name){if(!confirm('确认恢复数据库备份？'))return;try{const data=await api('/api/admin/database/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:name})});setStatus('dbStatus','已恢复：'+data.backup,true);loadStatus()}catch(e){setStatus('dbStatus',e.message)}}
checkSession();
